version: '3'
services:
  webserver:
    extends:
      file: docker-compose.yml
      service: webserver
    volumes:
      - ./app:/var/www

  certbot:
    extends:
      file: docker-compose.yml
      service: certbot
  
  app:
    extends:
      file: docker-compose.yml
      service: app
    build:
      context: app
      dockerfile: Dockerfile.dev
    environment:
      SERVICE_TAGS: dev
    volumes:
      - ./app:/var/www
  

networks:
  app-network:
    driver: bridge


volumes:
  dbdata:
    driver: local