version: '3'
services:

  #PHP Service
  app:
    build:
      context: app
      dockerfile: Dockerfile.prod
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www
    networks:
      - app-network
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini


  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    depends_on:
      - app
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./app:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

#Docker Networks
networks:
  app-network:
    driver: bridge
    
#Volumes
volumes:
  dbdata:
    driver: local