version: '3'
services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    depends_on:
      - app
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      -  /etc/ssl/certs/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
      - /home/nikita/csr:/digital.gov.ru
      - ./app:/var/www

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
      - ./app:/var/www
    depends_on:
      - webserver
    command: certonly --webroot -w /var/www/public -d nmedv.ru -d www.nmedv.ru -v
  
  app:
    build:
      context: app
      dockerfile: Dockerfile.dev
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: app
    working_dir: /var/www
    networks:
      - app-network
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./app:/var/www

networks:
  app-network:
    driver: bridge

